from dataclasses import dataclass


MARKETTWITS = "markettwits"
MOEX_DERIVATIVES = "moex_derivatives"
MARKETSNAPSHOT = "marketsnapshot"
FINAM_ALERT = "finamalert"
FINAM_INVEST = "finam_invest"
FINAM = "finam"
BCS_EXPRESS = "bcs_express"
BCS_EXPRESS_TG = "bcs_express_tg"
T_INVEST = "t_invest"


@dataclass(frozen=True)
class NewsRule:
    symbol: str
    category: str
    keywords: tuple[str, ...]
    long_terms: tuple[str, ...]
    short_terms: tuple[str, ...]
    block_terms: tuple[str, ...] = ()
    priority: int = 1


@dataclass(frozen=True)
class ChannelRule:
    channel: str
    source_weight: int
    default_ttl_minutes: int
    can_block_entries: bool
    speed_score: float
    reliability_score: float
    source_type: str
    display_name: str


CHANNEL_RULES: dict[str, ChannelRule] = {
    MARKETTWITS: ChannelRule(
        channel=MARKETTWITS,
        source_weight=1,
        default_ttl_minutes=45,
        can_block_entries=False,
        speed_score=0.95,
        reliability_score=0.78,
        source_type="telegram",
        display_name="MarketTwits",
    ),
    MARKETSNAPSHOT: ChannelRule(
        channel=MARKETSNAPSHOT,
        source_weight=2,
        default_ttl_minutes=60,
        can_block_entries=False,
        speed_score=0.92,
        reliability_score=0.82,
        source_type="telegram",
        display_name="MarketSnapshot",
    ),
    MOEX_DERIVATIVES: ChannelRule(
        channel=MOEX_DERIVATIVES,
        source_weight=3,
        default_ttl_minutes=90,
        can_block_entries=True,
        speed_score=0.55,
        reliability_score=0.98,
        source_type="official",
        display_name="Мосбиржа деривативы",
    ),
    FINAM_ALERT: ChannelRule(
        channel=FINAM_ALERT,
        source_weight=3,
        default_ttl_minutes=120,
        can_block_entries=False,
        speed_score=0.90,
        reliability_score=0.88,
        source_type="broker_telegram",
        display_name="Финам Alert",
    ),
    FINAM_INVEST: ChannelRule(
        channel=FINAM_INVEST,
        source_weight=3,
        default_ttl_minutes=180,
        can_block_entries=False,
        speed_score=0.82,
        reliability_score=0.90,
        source_type="broker_telegram",
        display_name="Финам Invest",
    ),
    FINAM: ChannelRule(
        channel=FINAM,
        source_weight=3,
        default_ttl_minutes=180,
        can_block_entries=False,
        speed_score=0.65,
        reliability_score=0.92,
        source_type="broker",
        display_name="Финам",
    ),
    BCS_EXPRESS: ChannelRule(
        channel=BCS_EXPRESS,
        source_weight=3,
        default_ttl_minutes=180,
        can_block_entries=False,
        speed_score=0.65,
        reliability_score=0.90,
        source_type="broker",
        display_name="БКС Экспресс",
    ),
    BCS_EXPRESS_TG: ChannelRule(
        channel=BCS_EXPRESS_TG,
        source_weight=3,
        default_ttl_minutes=150,
        can_block_entries=False,
        speed_score=0.88,
        reliability_score=0.88,
        source_type="broker_telegram",
        display_name="БКС Экспресс",
    ),
    T_INVEST: ChannelRule(
        channel=T_INVEST,
        source_weight=2,
        default_ttl_minutes=180,
        can_block_entries=False,
        speed_score=0.60,
        reliability_score=0.88,
        source_type="broker",
        display_name="Т-Инвестиции",
    ),
}


COMMON_LONG_TERMS = (
    "рост",
    "вырос",
    "выросла",
    "поддержка",
    "позитив",
    "позитивно",
    "сильный спрос",
    "дефицит",
    "бычий",
    "растёт",
    "растет",
    "подрастает",
    "ускорение вверх",
    "обновил максимум",
    "дивиденды",
    "снижение ставки",
    "эскалация",
    "риск перебоев поставок",
)

COMMON_SHORT_TERMS = (
    "падение",
    "снижение",
    "негатив",
    "негативно",
    "слабость",
    "давление",
    "давит",
    "под давлением",
    "санкции",
    "снижение спроса",
    "медвежий",
    "ускорение вниз",
    "обновил минимум",
    "рост ставки",
    "деэскалация",
)

COMMON_BLOCK_TERMS = (
    "приостановка",
    "изменение режима торгов",
    "изменение параметров риска",
    "повышение гарантийного обеспечения",
    "ограничение",
    "неторговый",
    "дискретный аукцион",
)


NEWS_RULES: tuple[NewsRule, ...] = (
    NewsRule(
        symbol="BMM6",
        category="нефть",
        keywords=(
            "нефть",
            "нефтяные котировки",
            "нефтяной рынок",
            "баррель",
            "баррель нефти",
            "черное золото",
            "brent",
            "brent crude",
            "ice brent",
            "марка brent",
            "североморская нефть",
            "цена нефти",
            "рынок нефти",
            "opec",
            "опек",
            "опек+",
            "opec+",
            "запасы нефти",
            "коммерческие запасы нефти",
            "eia",
            "минэнерго сша",
            "экспорт нефти",
            "добыча нефти",
            "нефтедобыча",
            "нефтепоставки",
            "$103",
            "$104",
            "$105",
        ),
        long_terms=COMMON_LONG_TERMS + ("сокращение добычи", "рост нефти", "дефицит нефти", "танкеры", "иран", "хуситы", "красное море", "ближний восток", "израиль", "военная операция", "удары", "превысила", "превысил", "выше"),
        short_terms=COMMON_SHORT_TERMS + ("рост запасов", "увеличение добычи", "избыток нефти", "добыча", "снизилась до", "ниже"),
        block_terms=COMMON_BLOCK_TERMS,
        priority=2,
    ),
    NewsRule(
        symbol="NGK6",
        category="газ",
        keywords=(
            "газ",
            "природный газ",
            "natural gas",
            "natgas",
            "henry hub",
            "газовый рынок",
            "lng",
            "спг",
            "ttf",
            "поставки газа",
            "рынок газа",
            "газовые хранилища",
            "хранилища газа",
            "запасы газа",
            "газпром",
        ),
        long_terms=COMMON_LONG_TERMS + ("холод", "жара", "дефицит газа", "снижение запасов", "запасы газа снижаются", "европа", "погода", "превысила", "превысил"),
        short_terms=COMMON_SHORT_TERMS + ("тёплая погода", "рост запасов газа", "слабый спрос", "европа", "погода", "снизилась до", "ниже"),
        block_terms=COMMON_BLOCK_TERMS,
        priority=2,
    ),
    NewsRule(
        symbol="GNM6",
        category="золото",
        keywords=(
            "золото",
            "драгметаллы",
            "драгоценные металлы",
            "золотые котировки",
            "цена золота",
            "унция золота",
            "gold",
            "xau",
            "xau/usd",
            "gold futures",
            "safe haven",
            "защитный актив",
            "защитные активы",
            "фрс",
            "серебро",
        ),
        long_terms=COMMON_LONG_TERMS + ("risk-off", "слабый доллар", "мягкая фрс", "геополитика", "геополитический риск", "иран", "израиль", "ближний восток", "хуситы", "военная операция", "превысило", "превысил"),
        short_terms=COMMON_SHORT_TERMS + ("сильный доллар", "рост доходностей", "доходности", "risk-on", "снизилось до", "ниже"),
        block_terms=COMMON_BLOCK_TERMS,
        priority=2,
    ),
    NewsRule(
        symbol="USDRUBF",
        category="валюта",
        keywords=(
            "usd/rub",
            "usdrub",
            "доллар/рубль",
            "доллар к рублю",
            "курс доллара",
            "курс рубля",
            "валютная пара usd/rub",
            "доллар",
            "рубль",
            "российская валюта",
            "валютный рынок",
            "валютный курс",
            "валютная выручка",
            "экспортеры",
        ),
        long_terms=COMMON_LONG_TERMS + ("ослабление рубля", "рост доллара", "спрос на валюту"),
        short_terms=COMMON_SHORT_TERMS + ("укрепление рубля", "продажа валютной выручки", "экспортеры", "цб", "минфин", "ставка", "санкции"),
        block_terms=COMMON_BLOCK_TERMS,
        priority=3,
    ),
    NewsRule(
        symbol="CNYRUBF",
        category="валюта",
        keywords=(
            "cny/rub",
            "cnyrub",
            "юань/рубль",
            "юань к рублю",
            "курс юаня",
            "курс cny",
            "китайская валюта",
            "юань",
            "китайский юань",
            "валютный рынок",
            "расчеты в юанях",
            "импорт из китая",
        ),
        long_terms=COMMON_LONG_TERMS + ("ослабление рубля", "рост юаня", "спрос на юань", "китай", "расчеты", "превысил", "превысила", "выше"),
        short_terms=COMMON_SHORT_TERMS + ("укрепление рубля", "слабость юаня", "китай", "расчеты", "снизился до", "ниже"),
        block_terms=COMMON_BLOCK_TERMS,
        priority=3,
    ),
    NewsRule(
        symbol="UCM6",
        category="валюта",
        keywords=(
            "usd/cny",
            "usdcny",
            "доллар/юань",
            "доллар к юаню",
            "курс доллара к юаню",
            "китайский юань",
            "юань",
            "cny",
            "народный банк китая",
            "китайская валюта",
            "валюта китая",
        ),
        long_terms=COMMON_LONG_TERMS + ("ослабление юаня", "сильный доллар", "давление на cny", "китай", "пошлины", "торговые войны", "выше"),
        short_terms=COMMON_SHORT_TERMS + ("укрепление юаня", "слабый доллар", "поддержка юаня", "китай", "стимулы", "ниже"),
        block_terms=COMMON_BLOCK_TERMS,
        priority=3,
    ),
    NewsRule(
        symbol="IMOEXF",
        category="индекс",
        keywords=(
            "imoex",
            "индекс мосбиржи",
            "индекс мосбиржи imoex",
            "московская биржа индекс",
            "индекс российского рынка",
            "мосбиржа",
            "российский рынок акций",
            "рынок акций рф",
            "акции рф",
            "индекс moex",
        ),
        long_terms=COMMON_LONG_TERMS + ("дивиденд", "позитив по рынку", "рост рынка", "рынок рф", "российский рынок"),
        short_terms=COMMON_SHORT_TERMS + ("негатив по рынку", "геополитический риск", "давление на рынок", "рынок рф", "российский рынок"),
        block_terms=COMMON_BLOCK_TERMS,
        priority=2,
    ),
    NewsRule(
        symbol="RNM6",
        category="нефтянка",
        keywords=(
            "роснефть",
            "rosneft",
            "акции роснефти",
            "rosn",
            "нефтяной сектор",
            "экспорт нефти",
            "нефтянка",
            "нефтегазовый сектор",
            "нефтяные компании",
            "российская нефть",
        ),
        long_terms=COMMON_LONG_TERMS + ("сильная отчетность", "дивиденды", "рост цен на нефть", "налоговые льготы", "экспорт", "байбэк"),
        short_terms=COMMON_SHORT_TERMS + ("слабая отчетность", "падение нефти", "санкции", "давление на нефтяной сектор", "снижение экспорта"),
        block_terms=COMMON_BLOCK_TERMS,
        priority=2,
    ),
    NewsRule(
        symbol="SRM6",
        category="банки",
        keywords=(
            "сбер",
            "sber",
            "сбербанк",
            "sberbank",
            "акции сбера",
            "акции сбербанка",
            "обыкновенные акции сбера",
            "банковский сектор",
            "банки",
            "финансовый сектор",
        ),
        long_terms=COMMON_LONG_TERMS + ("сильная отчетность", "дивиденды сбера", "рост прибыли", "банковский сектор", "кредитование"),
        short_terms=COMMON_SHORT_TERMS + ("санкции на банки", "слабая отчетность", "давление на банковский сектор", "банковский сектор", "кредитование"),
        block_terms=COMMON_BLOCK_TERMS,
        priority=2,
    ),
    NewsRule(
        symbol="VBM6",
        category="банки",
        keywords=(
            "втб",
            "vtb",
            "банк втб",
            "акции втб",
            "vtbr",
            "втб банк",
            "банковский сектор",
            "банки",
            "финансовый сектор",
        ),
        long_terms=COMMON_LONG_TERMS + ("сильная отчетность", "рост прибыли", "банковский сектор", "дивиденды", "кредитование"),
        short_terms=COMMON_SHORT_TERMS + ("слабая отчетность", "санкции на банки", "давление на банковский сектор", "допэмиссия"),
        block_terms=COMMON_BLOCK_TERMS,
        priority=2,
    ),
    NewsRule(
        symbol="RBM6",
        category="облигации",
        keywords=(
            "rgbi",
            "индекс гособлигаций",
            "индекс облигаций",
            "гособлигации",
            "госбумаги",
            "офз",
            "доходности офз",
            "рынок облигаций",
            "облигации",
            "долговой рынок",
            "ключевая ставка",
            "ставка цб",
            "цб рф",
            "минфин",
        ),
        long_terms=COMMON_LONG_TERMS + ("снижение доходностей", "спрос на офз", "мягкая риторика цб", "снижение ставки", "рост облигаций"),
        short_terms=COMMON_SHORT_TERMS + ("рост доходностей", "жесткая риторика цб", "рост ставки", "давление на офз", "снижение облигаций"),
        block_terms=COMMON_BLOCK_TERMS,
        priority=2,
    ),
)
